[tool.pytest.ini_options]
testpaths        = ["tests"]
pythonpath       = ["src", ".."]
addopts          = "--tb=short -q --cov=src --cov-report=term-missing"

[tool.coverage.run]
source = ["src"]
omit   = ["tests/*"]
